apiVersion: v1
kind: Service
metadata:
  name: service-management-frontend-svc
  namespace: service-management
spec:
  selector:
    app: service-management-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
  type: ClusterIP
