import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
import { fonts } from './fonts'
import { DefaultLayout } from '@/components/layout/default'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={fonts.dm_Sans.className}>
      <body>
        <Providers>
          <DefaultLayout>{children}</DefaultLayout>
        </Providers>
      </body>
    </html>
  )
}
